[workspace]
resolver = "2"
members = [
  "yamux",
  "secio",
  "multiaddr",
  "tentacle",
  "bench",
]
exclude = [
  "protocols/discovery",
  "protocols/identify",
  "protocols/ping",
  "simple_wasm"
]
